config/routes.rb
Guia3::Application.routes.draw do
  
    resources :cursos do
    resources :estudiantes 
  end

    resources :materias do
    resources :instructores
  end

  

   get "pages/index"
   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "signup" => "users#new", :as => "signup"
   resources :users 
   resources :sessions
   resources :cursos
   resources :materias
   resources :pages
   resources :horarios, :pdf
   root :to => 'pages#index'
  

  root :to => 'pages#index'

end

app/models/horario.rb
class Horario < ActiveRecord::Base
    validates :aula, :presence => true
    validates :dia, :presence => true
    validates :instructor, :presence => true 
    validates :curso, :presence => true
    validates :materia, :presence => true


  belongs_to :materia
  belongs_to :curso
  belongs_to :instructor
  attr_accessible :dia, :aula, :hora, :materia_id, :instructor_id, :curso_id

  def self.search(search)
	where('aula like ?',"%#{search}%")
	end
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController

  before_filter :require_login
  load_and_authorize_resource :only => [:new, :edit, :destroy]
  helper_method :sort_column, :sort_direction
  
  def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

   if ((@nrp) <= 0)
     @nrp = 3
   end
    @horarios = Horario.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page]).order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html
      format.xml { render :xml => @horarios }
    end
  end


  def show
      @horario = Horario.find(params[:id])   

     if params[:format] == "pdf"
          pdf = HorarioPdf.new(@horario, view_context)
          send_data pdf.render, filename:
          "horario_#{@horario.id}.pdf", 
          type: "application/pdf"
      end
  end

  def new
      @horario= Horario.new
  end

  def edit
      @horario = Horario.find(params[:id])
  end

  def create
      @horario= Horario.new(params[:horario])
      render :action => :new unless @horario.save
      @horarios =Horario.all
  end

   def update
      @horario = Horario.find(params[:id])
      render :action => :edit unless @horario.update_attributes(params[:horario])
  end

  def destroy
      @horario = Horario.find(params[:id])
      @horario.destroy
      @horarios = Horario.all
  end
  
  private
  def sort_column
    Horario.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/horarios_helper.rb
module HorariosHelper
	def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/horarios/_form.html.erb
<%= simple_form_for(@horario, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>

  <%= f.input :dia, as: :date, start_year: Date.today.year - 50, end_year: Date.today.year - 0, accept_day: true, order: [:day, :month, :year] %>
  <%= f.input :hora,:class=>"input-mini", :label => "Hora" %>

  <%= f.input :aula, collection:["aula1","aula2","aula3"] %>
  
  <!-- coleccion lixbox  -->
  <%= f.label :materia  %>
  <%= f.collection_select :materia_id, Materia.all, :id, :nombre %><br><br>
  
  <%= f.label :instructor %>
  <%= f.collection_select :instructor_id, Instructor.all, :id, :nombre %><br><br>

  <%= f.label :curso %>
  <%= f.collection_select :curso_id, Curso.all, :id, :nombre %><br>
  

  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', horarios_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/horarios/_horario.html.erb
<tr id=<%= "horario_#{horario.id}" %>>
  <td><%= horario.dia %></td>
  <td><%= horario.hora %></td>
  <td><%= horario.aula %></td>
  <td><%= horario.materia.nombre %></td>
  <td><%= horario.instructor.nombre %></td>
  <td><%= horario.curso.nombre %></td>
  <td>

    <%= link_to 'Mostrar', horario, :remote => true, :class => 'btn btn-mini' %>

    <%= link_to 'Editar', edit_horario_path(horario), :remote => true,
        :class => 'btn btn-mini' %>
        
    <%= link_to 'Eliminar', horario, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
        <%= link_to "pdf", horario_path(horario, :format => "pdf"), :class => 'btn btn-mini btn-inverse' %>
  </td>
</tr>
       

app/views/horarios/_show.html.erb
<%- model_class = Horario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='horario'>
  <p><%= @horario.dia %></p>
  <p><%= @horario.hora %></p>
  <p><%= @horario.aula %></p>
  <p><%= @horario.materia.nombre %></p>
  <p><%= @horario.instructor.nombre %></p>
  <p><%= @horario.curso.nombre %></p>
</div>

app/views/horarios/create.js.erb
$('table tbody').append("<%= escape_javascript(render @horario) %>")
$("input#totalregs").attr('value','<%= @horarios.count %>');
$.lazybox.close()

app/views/horarios/destroy.js.erb
$("table tr#horario_<%= @horario.id %>").remove();
$("input#totalregs").attr('value','<%= @horarios.count %>');

app/views/horarios/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/horarios/index.html.erb
<%- model_class = Horario -%>
<div class="page-header">
   <br>
  <br>
  <center><h1>Horarios</h1></center>
  <%= form_tag request.path, :method => 'get' do %>
    Datos a Buscar:
    <div class="input-append">
      <%= search_field_tag :search,params[:search], option ={:class=>"span2", :placeholder => "dia, aula"} %>
      <%= submit_tag "Consultar", :class => "btn btn-inverse", :nombre => nil %>
    </div>  
    <p>numero de registros:
   <p><%= text_field_tag :registro, params[:registro], options={:class=>"span1"} %></p>
    <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <% end %>
</div>
<table class="table table-striped table-bordered table-condensed pretty">
  <thead>
    <tr>
      <th><%= sortable "dia" %></th>
      <th><%= sortable "hora" %></th>
      <th><%= sortable "aula" %></th>
      <th><%= sortable "materia" %></th>
      <th><%= sortable "instructor" %></th>
      <th><%= sortable "curso" %></th>
    <th>Acciones</th> 
    </tr>
  </thead>
  <tbody>
     <%= render @horarios %>
  </tbody>
</table>
<tr>
  <td><%= link_to 'Nuevo Horario', new_horario_path, :class => "btn btn-primary btn-mini", :remote => true %></td>
</tr>
<div class="pagination pagination-centered">
  <ul>
    <%= will_paginate @horarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  <p>
    <td>Total Horarios :<input type="text"  id="totalregs" class="span1" value="<%= @horarios.total_entries %>" readonly />

  </p>
</div>

app/views/horarios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/horarios/show.js.erb
$.lazybox("<%= j(render 'show') %>", {cerrar: true, klass: 'sticker', fixed: true})

app/views/horarios/update.js.erb
$('tr#horario_<%= @horario.id %>').replaceWith("<%= escape_javascript(render @horario) %>")
$.lazybox.close()