config/routes.rb
Guia3::Application.routes.draw do
  
    resources :cursos do
    resources :estudiantes 
  end

    resources :materias do
    resources :instructores
  end

  

   get "pages/index"
   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "signup" => "users#new", :as => "signup"
   resources :users 
   resources :sessions
   resources :cursos
   resources :materias
   resources :pages
   resources :horarios, :pdf
   root :to => 'pages#index'
  

  root :to => 'pages#index'

end

app/models/curso.rb
class Curso < ActiveRecord::Base
	validates :nombre, :presence => true,
	  :length => {:minimum =>3, :maximum => 80 }

	validates :ficha, :presence => true,
	:length => { :minimum => 4, :maximum => 10 },
	:numericality => true

 
  has_many :horarios, :dependent => :destroy
  has_many :estudiante, :dependent => :destroy
  attr_accessible :ficha, :nombre 

  def self.search(search)
	where('nombre like ? or ficha like ?', "%#{search}%","%#{search}%")
	end
	
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  
    before_filter :require_login
   load_and_authorize_resource :only => [:new, :edit, :destroy]
    before_filter :find_curso, :except => [ :index, :create, :new ]
    helper_method :sort_column, :sort_direction

def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

    if ((@nrp) <= 0)
     @nrp = 3
   end
    @cursos = Curso.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page]).order(sort_column + " " + sort_direction)

      respond_to do |format|
      format.html 
      format.xml { render :xml => @cursos }
    end
  end

  def new
      @curso = Curso.new
  end

  def create
      @curso = Curso.new(params[:curso])
      render :action => :new unless @curso.save
      @cursos = Curso.all
  end

  def update
      render :action => :edit unless @curso.update_attributes(params[:curso])
  end

  def destroy
      @curso = Curso.find(params[:id])
      @curso.destroy
      @cursos =Curso.all
  end

  private

  def find_curso
      @curso = Curso.find(params[:id]) if params[:id]
  end
 
  def sort_column
    Curso.column_names.include?(params[:sort]) ? params[:sort] : "nombre"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  
end

app/helpers/cursos_helper.rb
module CursosHelper
	 def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/cursos/_curso.html.erb
<tr id=<%= "curso_#{curso.id}" %>>
  <td><%= curso.ficha %></td>
  <td><%= curso.nombre %></td>
  <td>
    <%= link_to 'Mostrar', curso, :remote => true, :class => 'btn btn-mini' %>
    <%= link_to 'Editar', edit_curso_path(curso), :remote => true,
        :class => 'btn btn-mini' %>
    <%= link_to 'Eliminar', curso, :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
  <td><%= link_to 'Estudiantes', curso_estudiantes_path(curso), :class=>"btn btn-inverse"%></td>
</tr>

app/views/cursos/_form.html.erb
<%= simple_form_for(@curso, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
 
  <%= f.input :nombre %>
  <%= f.input :ficha %>
 
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    
    <%= link_to 'Atras', cursos_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/cursos/_show.html.erb
<%- model_class = Curso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='team'>
 
  <p><b>nombres:</b><%= @curso.nombre %></p>
  <p><b>ficha:</b><%= @curso.ficha %></p>
</div>

app/views/cursos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @curso) %>");
$("input#totalregs").attr('value','<%= @cursos.count %>');
$.lazybox.close();

app/views/cursos/destroy.js.erb
$("table tr#curso_<%= @curso.id %>").remove();
$('input#totalregs').attr('value','<%= @cursos.count %>');

app/views/cursos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/cursos/index.html.erb
<%- model_class = Curso -%>
<div class="page-header">
  <br><br>
  <center><h1>Cursos</h1></center>
    <%= form_tag request.path, :method => 'get' do %>
      Datos a Buscar:
    <div class="input-append">
      <%= search_field_tag :search, params[:search], options ={ :class=>"span2", :placeholder => "Curso, ficha"} %>
      <%= submit_tag "Consultar", :class => "btn btn-inverse", :nombre => nil %>
    </div>
     <p>numero de registros:
   <p><%= text_field_tag :registro, params[:registro], options={:class=>"span1"} %></p>
    <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <% end %>
    <br>
</div>

<table class="table table-hover table-bordered table-condensed pretty" id="inv">
  <thead>
    <tr>
      <th><%= sortable "ficha" %></th>
      <th><%= sortable "nombre","Curso" %></th>
      <th> Acciones </th>
    </tr>
  </thead>
  <tbody>
     <%= render @cursos %>
  </tbody>
  <tfoot>
  </tfoot>
</table>
    <tr>
      <td><%= link_to 'Nuevo Curso', new_curso_path, :class => "btn btn-primary btn-mini", :remote => true %></td>
    </tr>
<br />
<br />
<div class="pagination pagination-centered">
  <ul>
    <%= will_paginate @cursos, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  <p>
  <td>Total Cursos :<input type="text"  id="totalregs" class="span1" value="<%= @cursos.total_entries %>" readonly />
</p>
</div>

app/views/cursos/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/cursos/show.js.erb
$.lazybox("<%= j(render 'show') %>", {cerrar: true, klass: 'sticker', fixed: true})

app/views/cursos/update.js.erb
$('tr#curso_<%= @curso.id %>').replaceWith("<%= escape_javascript(render @curso) %>");
$.lazybox.close();