config/routes.rb
Guia3::Application.routes.draw do
  
    resources :cursos do
    resources :estudiantes 
  end

    resources :materias do
    resources :instructores
  end

  

   get "pages/index"
   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "signup" => "users#new", :as => "signup"
   resources :users 
   resources :sessions
   resources :cursos
   resources :materias
   resources :pages
   resources :horarios, :pdf
   root :to => 'pages#index'
  

  root :to => 'pages#index'

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
	  belongs_to :curso

  attr_accessible :cedula, :direccion, :telefono, :email, :apellido, :nombre, :curso_id, :imagen
  
  validates :nombre, :presence=>true,
	:length => { :minimum =>3, :maximum => 80 }

  validates :apellido, :presence=>true,
  :length => { :minimum =>3, :maximum => 80 }

	validates :cedula, :presence => true,
  :length => { :minimum => 10, :maximum => 11 },
  :uniqueness => true, :numericality => true

	validates :email, :presence => true,
  :uniqueness => true,
  :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :direccion, :presence=>true

 

  
def self.search(search)
where('nombre like ? or cedula like ? or direccion like ? or email like ? ',"%#{search}%" ,"%#{search}%","%#{search}%","%#{search}%")
end

 has_attached_file :imagen, :styles => { :small => "150x150>", :lsmall => "30x30>" },
                  :url  => "/assets/estudiantes/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/estudiantes/:id/:style/:basename.:extension"


validates_attachment_presence :imagen
validates_attachment_size :imagen, :less_than => 5.megabytes
validates_attachment_content_type :imagen, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController

  before_filter :require_login
  load_and_authorize_resource :only => [:new, :edit, :destroy]
  before_filter :find_curso_estudiantes
  helper_method :sort_column, :sort_direction

  def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

   if ((@nrp) <= 3)
     @nrp = 3
   end
     
      @estudiantes = @curso.estudiante.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page]).order(sort_column + " " + sort_direction)
      respond_to do |format|
      format.html 
      format.xml { render :xml => @estudiantes }
    end
  end

  def new
     @estudiante =  Estudiante.new
  end

  def create
     @estudiante = @curso.estudiante.build(params[:estudiante])
     render :action => :new unless @estudiante.save
     @estudiantes = Estudiante.all
 end

  def update
    @estudiante = Estudiante.find(params[:id])
    render :action => :edit unless @estudiante.update_attributes(params[:estudiante])
  end

  def destroy
    @estudiante = Estudiante.find(params[:id])
    @estudiante.destroy
    @estudiantes =Estudiante.all
  end

  private

  def find_curso_estudiantes
     @curso = Curso.find(params[:curso_id])
     @estudiante = Estudiante.find(params[:id]) if params[:id]
  end


  def sort_column
    Estudiante.column_names.include?(params[:sort]) ? params[:sort] : "nombre"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
    def display_base_errors resource
        return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
            messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
            html = <<-HTML
            <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">&#215;</button>#{messages}
            </div>
            HTML
            html.html_safe
    end
end

app/views/estudiantes/_estudiante.html.erb
<tr id=<%= "estudiante_#{estudiante.id}" %>>
  <td><%= image_tag estudiante.imagen.url(:lsmall) %></td>
  <td><%= estudiante.nombre %></td>
  <td><%= estudiante.apellido %></td>
  <td><%= estudiante.cedula %></td>
  <td><%= estudiante.telefono %></td>
  <td><%= estudiante.email %></td>
  <td><%= estudiante.direccion %></td>
  <td><%= estudiante.curso.nombre %></td>
  
  <td>
  <%= link_to "Inormacion", curso_estudiante_path(@curso,estudiante), :remote => true, :class => 'btn btn-info btn-mini' %>

  <%= link_to "Editar", edit_curso_estudiante_path(@curso,estudiante), :remote => true, :class => 'btn btn-danger btn-mini' %>
  
  <%= link_to "Eliminar", curso_estudiante_path(@curso, estudiante), :data => { :confirm => 'Esta Seguro?' },
  :method => :delete, :remote => true, :class => 'btn btn-mini btn-warning' %>
  </td>
</tr>


 

app/views/estudiantes/_form.html.erb
<%= simple_form_for([@curso,@estudiante ], :html => { :multipart => true, :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  
  
  <%= f.file_field :imagen %>
  <%= f.input :nombre, :label => "Nombre"  %>
  <%= f.input :apellido, :label => "Apellido" %>
  <%= f.input :cedula, :label => "Cedula"  %>
  <%= f.input :telefono, :label => "Telefono"  %>
  <%= f.input :email, :label => "Email"  %>
  <%= f.input :direccion, :label => "Direccion"  %>
  <br>
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    
    <%= link_to "Atras", curso_estudiantes_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/estudiantes/_show.html.erb
<%- model_class = Estudiante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='estudiante'>
 <%= image_tag @estudiante.imagen.url(:small) %><br>
  <p>Nombre: <%= @estudiante.nombre %></p>
  <p>Apellido: <%= @estudiante.apellido %></p>
  <p>Cedula: <%= @estudiante.cedula %></p>
  <p>Email: <%= @estudiante.email %></p>
  <p>Direccion: <%= @estudiante.direccion %></p>
  <p>curso: <%= @estudiante.curso_id %></p>
</div>

app/views/estudiantes/create.js.erb
$('table tbody').append("<%= escape_javascript(render @estudiante) %>")
$("input#totalregs").attr("value','<%= @estudiantes.count %>");
$.lazybox.close()

app/views/estudiantes/destroy.js.erb
$("table tr#estudiante_<%= @estudiante.id %>").remove();
$("input#totalregs").attr('value','<%= @estudiantes.count %>');

app/views/estudiantes/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/estudiantes/index.html.erb
<%- model_class = Estudiante -%>
  <div class="page-header">
 <center><h1>Estudiantes del curso <%= @curso.nombre %></h1></center>
 <br>

  <%= form_tag request.path, :method => 'get' do %>
    Datos a Buscar:
    <div class="input-append">
      <%= search_field_tag :search, params[:search], :placeholder => "nombre, cedula, direccion, email" %>
      <%= submit_tag "Consultar", :class => "btn btn-inverse ", :name => nil %>
    </div>
    <p>numero de registros
   <p><%= text_field_tag :registro, params[:registro], options={:class=>"span1"} %></p>
   <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <% end %>
    <br>
</div>
  <table class="table table-hover table-bordered table-condensed pretty ">
      <th>Imagen</th>
      <th><%= sortable "nombre" %></th>
      <th><%= sortable "apellido" %></th>
      <th><%= sortable "cedula","Documento" %></th>
      <th><%= sortable "telefono","Telefono" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "direccion" %></th>
      <th><%= sortable "curso_id","Curso" %></th>
  <th>Acciones</th>
 </tr>
        </thead>
        <tbody>
          <%= render @estudiantes %>
        </tbody>
      </table>
      <tr>
        <td><%= link_to "Nuevo Estudiante", new_curso_estudiante_path, :class=>"btn btn-primary btn-mini",:remote => true %> </td>
        <td><%= link_to "Curso", cursos_path , :class => 'btn btn-mini btn-inverse' %></td>
      </tr>
  
    <div class="pagination pagination-centered">
    <ul>
    <%= will_paginate @estudiantes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
    <td>Total estudiantes: <%=@estudiantes.total_entries %> </td>
  </div>

app/views/estudiantes/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %> ");

app/views/estudiantes/show.js.erb
$.lazybox("<%= j(render 'show') %>", {cerrar: true, klass: 'sticker', fixed: true})

app/views/estudiantes/update.js.erb
$('tr#estudiante_<%= @estudiante.id %>').replaceWith("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()