config/routes.rb
Guia3::Application.routes.draw do
  
    resources :cursos do
    resources :estudiantes 
  end

    resources :materias do
    resources :instructores
  end

  

   get "pages/index"
   get "logout" => "sessions#destroy", :as => "logout"
   get "login" => "sessions#new", :as => "login"
   get "signup" => "users#new", :as => "signup"
   resources :users 
   resources :sessions
   resources :cursos
   resources :materias
   resources :pages
   resources :horarios, :pdf
   root :to => 'pages#index'
  

  root :to => 'pages#index'

end

app/views/layouts/_messages.html.erb
<div id="msg">
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
<a class="close" data-dismiss="alert">&#215;</a>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<ul class="nav">
	<% if current_user %>
	<li>
	<%= link_to('Cursos', cursos_path) %>
	</li>
	<li>
	<%= link_to('Materias', materias_path) %>
	</li>
	<li>
	<%= link_to('Horarios', horarios_path) %>
	</li>
	<div id="pos">
	<b>Usuario:</b>	 <%= current_user.username %>
       <%= link_to "cerrar sesion", logout_path, :class=>"btn btn-mini btn-primary" %>
      <% else %>
       <!--<%= link_to "Crear cuenta", signup_path, :class=>"btn btn-mini btn-primary" %> 
       <%= link_to "iniciar sesion", login_path, :class=>"btn btn-mini btn-primary" %></div>-->


      <% end %>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "guia3" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>    
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    
  </head>
  <body>
   <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
           <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
           </a>
           <%= link_to image_tag("home.png"), root_path, :class => 'brand' %>
           <div class="nav-collapse">
                <%= render 'layouts/navigation' %>
                
           </div>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <br><br>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>